name: Build and attach to tag on new tag

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check it
        uses: actions/checkout@v2
      
      - name: Node it
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Dep' it
        run: npm install
        
      - name: Build it
        run: npm run build

      - name: Zip it
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r twitchrato.zip build
          
      - name: Release it
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      
      - name: Up' it
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./twitchrato.zip
          asset_name: "./twitchrato-${{ github.ref }}.zip"
          asset_content_type: application/zip
